# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f06a2b38951c1517e491005e4506f3876f03b16ce37b4adfdd5739d11deba033fd30e5b194057cc8eb1be71ac56daae00031f81972695a5d7b20a6c4200f0c78

test:
  secret_key_base: 1698e5e8ad6aa9205c6e6efc2d93926b978944ed6fb82e3eb7402f2c8bebd71a704939d7a16af7a9058ecaac9ad5df323be7d120fffe442d5899d498360f4595

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
